import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { useEffect } from "react";
import { AppProps } from "next/app";
// import { auth } from "../lib/firebase";
// import { useAuthState } from "react-firebase-hooks/auth";
// import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [user, loading] = useAuthState(auth);

  // useEffect(() => {
  //   if (user) {
  //     // User is signed in, redirect to dashboard or home page
  //   } else {
  //     // User is signed out, redirect to login page
  //   }
  // }, [user]);

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
